trigger:
- main

variables:
  solution: '**/*.sln'
  projects: |
    **/Beacon.WebHost.csproj
    **/BeaconUI.WebApp.csproj
  buildConfiguration: 'Release'

pool: 
  vmImage: 'windows-latest'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      useGlobalJson: true

  - task: DotNetCoreCLI@2
    displayName: 'Restore dependencies'
    inputs:
      command: 'restore'
      projects: '$(projects)'

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: build
      projects: '$(projects)'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      command: test
      projects: '**/tests/**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Install EF Core Tools'
    inputs:
      command: custom
      custom: tool
      arguments: install --global dotnet-ef

  - task: DotNetCoreCLI@2
    displayName: 'Generate Db Migrations Script'
    inputs:
      command: 'custom'
      custom: 'ef'
      arguments: migrations script --idempotent --output $(Build.ArtifactStagingDirectory)/Migrations.sql --project ./src/Server/Beacon.API/Beacon.API.csproj --startup-project ./src/Server/Beacon.WebHost/Beacon.WebHost.csproj

  - task: DotNetCoreCLI@2
    displayName: 'Publish web app'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/Beacon.WebHost.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'